CREATE TABLE IF NOT EXISTS agent_diagnostic_task (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  task_id VARCHAR(64) NOT NULL COMMENT '对外暴露的业务任务ID',
  task_type VARCHAR(32) NOT NULL DEFAULT 'AI_OPS' COMMENT '任务类型',
  scene_code VARCHAR(64) NOT NULL DEFAULT 'AI_OPS' COMMENT '场景编码',
  status VARCHAR(16) NOT NULL COMMENT '任务状态',
  trigger_source VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '触发来源',
  session_id VARCHAR(64) DEFAULT NULL COMMENT '关联会话ID',
  request_payload LONGTEXT DEFAULT NULL COMMENT '请求快照(JSON字符串)',
  input_summary VARCHAR(500) DEFAULT NULL COMMENT '输入摘要',
  planner_output LONGTEXT DEFAULT NULL COMMENT 'Planner最终输出',
  final_report LONGTEXT DEFAULT NULL COMMENT '最终诊断报告',
  error_code VARCHAR(64) DEFAULT NULL COMMENT '错误码',
  error_message TEXT DEFAULT NULL COMMENT '错误信息',
  model_name VARCHAR(128) DEFAULT NULL COMMENT '本次使用的模型名',
  tool_summary LONGTEXT DEFAULT NULL COMMENT '工具调用摘要(JSON字符串)',
  started_at DATETIME(3) DEFAULT NULL COMMENT '开始执行时间',
  finished_at DATETIME(3) DEFAULT NULL COMMENT '结束执行时间',
  duration_ms BIGINT DEFAULT NULL COMMENT '总耗时毫秒',
  created_by VARCHAR(64) DEFAULT NULL COMMENT '创建人/调用方',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
  PRIMARY KEY (id),
  UNIQUE KEY uk_task_id (task_id),
  KEY idx_status_started_at (status, started_at),
  KEY idx_task_type_started_at (task_type, started_at),
  KEY idx_session_id (session_id),
  KEY idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Agent诊断任务主表';
