CREATE TABLE IF NOT EXISTS tool_config (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  tool_name VARCHAR(64) NOT NULL COMMENT '工具名',
  enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_tool_name (tool_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工具开关配置表';
